#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

find "$install_dir" -type f -exec chmod 660 {} \;
find "$install_dir" -type d -exec chmod 750 {} \;
find "$install_dir" -type d -exec chmod +s {} \;

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app ..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Finalizing installation..."

installLanguage="$language"
installUrl="/?install/postinstall/$installLanguage"
installId="$admin"
installPassword="${password}"
installMail=$(ynh_user_get_info --username="$admin" --key=mail)
installFirstname=$(ynh_user_get_info --username="$admin" --key=fullname | awk  -F' ' '{print $1}')
installLastname=$(ynh_user_get_info --username="$admin" --key=fullname | awk  -F' ' '{print $2}')

csrf=$(ynh_local_curl "${installUrl}" | grep "csrf" | awk -F'value="' '{print $2}' | awk -F'"' '{print $1}')

ynh_local_curl "${installUrl}" "csrf=${csrf}" "installId=${installId}" "installPassword=${installPassword}" "installConfirmPassword=${installPassword}" "installMail=${installMail}" "installFirstname=${installFirstname}" "installLastname=${installLastname}" "installLanguage=${installLanguage}"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
