#!/bin/bash

source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=php_upload_max_filesize --value=256M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
# Remove updateAvailable flag
ynh_replace --match='"updateAvailable":true' --replace='"updateAvailable":false' --file="$install_dir/site/data/core.json"
ynh_replace --match='"updateModuleAvailable":true' --replace='"updateModuleAvailable":false' --file="$install_dir/site/data/core.json"

# Disable autoUpdate
ynh_replace --match='"autoUpdate":true' --replace='"autoUpdate":false' --file="$install_dir/site/data/config.json"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
